export const styles = {
  inputContainer: {
    borderRadius: "5px",
    border: "1px solid #3A3F50",
    backgroundColor: "#292B39",
    padding: "30px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
  },
  input: {
    paddingLeft: "15px",
    paddingRight: "15px",
    color: "white",
    border: "1px solid #3A3F50",
    backgroundColor: "#11131B",
    borderRadius: "5px",
    height: "40px",
    width: "350px",
    marginBottom: "20px",
  },
  loginButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    cursor: "pointer",
    backgroundColor: "#7e1bb9",
    color: "white",
    borderRadius: "5px",
    height: "40px",
    width: "350px",
  },
};
